%Transformation matrix from the particle/robot frame to the global frame
function tf = particleTransform(x, y, theta)
    tf = [cos(theta)   -sin(theta)   x; ...
          sin(theta)    cos(theta)   y; ...
                   0             0   1];
end